core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls)]
urlpatterns += i18n_patterns(
    path('', include('userform.urls')),
)+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

userform/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.home, name='home'),
    path("search/", views.search, name='search'),
]

userform/models.py
from django.db import models
import uuid


# Create your models here.
class UserEntry(models.Model):
    uuid = models.CharField(max_length=50)
    header = models.CharField(max_length=50)
    description = models.TextField(max_length=300)
    link = models.CharField(max_length=255)
    email = models.EmailField(max_length=254)
    image = models.ImageField(blank = True)
    created_date = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"{self.header}"

userform/forms.py
from django import forms
from django.db import models
from .models import UserEntry

class UserEntryForm(forms.ModelForm):
    class Meta:
        model = UserEntry
        fields = ('header', 'description', 'link', 'email', 'image', 'uuid')

    

userform/views.py
from django.shortcuts import render

from .forms import UserEntryForm
from .models import UserEntry
from django.http import JsonResponse

# Create your views here.
def home(request):
    data = {"uuid":""}
    if request.method == "POST":
        form = UserEntryForm(request.POST or None, request.FILES or None)
        if request.is_ajax():
            if form.is_valid():
                form.save()
                data['header'] = form.cleaned_data['header']
                data['uuid'] = form.cleaned_data['uuid']
                data['status'] = "success"
    else:
        form = UserEntryForm()
    context={
        'form': form,
        'uuid': data['uuid']
    }
    return render(request, 'userform/home.html', context)

def search(request):
    result = ""
    if 'q' in request.GET:
        search = request.GET['q']
        try:
            if search:
                result = UserEntry.objects.get(uuid=search)
        except UserEntry.DoesNotExist:
            context = {
                "result": result
            }
            return render(request, "userform/search.html", context)
            
    context = {
        'result': result,
    }

    return render(request, "userform/search.html", context)

templates/base.html
{% load static %}
{% load i18n %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <!--Custom Css-->
    <link href="{% static 'css/main.css' %}" rel="stylesheet" type="text/css"/>

    <title></title>
  </head>
  <body>
  

    <div class="container mt-3">
      {% block content %}
      
      {% endblock content %}
    </div>

    <script src={% static 'js/main.js' %} defer></script>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  </body>
</html>

templates/includes/alert.html
{% if messages %}
    {% for message in messages %}
    <div id="message" class="container">
        <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %} role="alert">
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span></button>
            {% if message.level == DEFAULT_MESSAGE_LEVELS.ERROR %}Error: {% endif %}
            {{ message }}
        </div>
    </div>
    {% endfor %}
{% endif %}

templates/includes/navbar.html
{% load i18n %}
<div class="card" id="navbarSupportedContent">
  <div class="card-body">
    <a href="{% url 'home' %}">{% trans "Ana Sayfa" %}</a><span> |</span>
    <a href="{% url 'search' %}">{% trans "Sorgula" %}</a>
    <form action="{% url 'search' %}" class="form-inline my-2 my-lg-0" method="GET">
      <input class="form-control mr-sm-2" type="search" placeholder="{% trans "Sorgula" %}" name="q" aria-label="{% trans "Sorgula" %}">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">{% trans "Sorgula" %}</button>
    </form>
    <span class="lang-bar">
      <a href="/tr">TR</a>
      <span>|</span>
      <a href="/en">EN</a>
    </span>
  </div>
</div>

    
    

templates/userform/home.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}


{% block content %}



<div class="mt-3 mx-5">
    
    
    <div class="card">
        <div class="card-body">
        {% include 'includes/navbar.html' %}
        
            <form action="" id="form-submit">
                {% csrf_token %}
                <label for="id_header">{% trans "Başlık" %}:</label>
                <input type="text" name="header" maxlength="50" placeholder="{% trans "Başlık" %}" class="form-control" required="" id="id_header">

                <label for="id_description">{% trans "Açıklama" %}:</label>
                <textarea name="description" cols="40" rows="4" maxlength="300" placeholder="{% trans "Açıklama" %}" class="form-control" required="" id="id_description"></textarea>

                <label for="id_link">{% trans "Link" %}:</label>
                <input type="text" name="link" maxlength="255" placeholder="{% trans "Link" %}" class="form-control" required="" id="id_link">

                <label for="id_email">{% trans "Email" %}:</label>
                <input type="email" name="email" maxlength="254" placeholder="{% trans "Email" %}" class="form-control" required="" id="id_email">

                <label for="id_header">{% trans "Resim" %}:</label>
                <input type="file" name="image" accept="image/*" class="form-control" id="id_image">

                <br>
                <div id="img-box"></div>
                
                <br>
                <br>
                <div id="alert-box"></div>
                <button type="submit" class="btn btn-primary">{% trans "Gönder" %}</button>
            </form>
            
        </div>
    </div>
    

</div>


{% endblock content %}

templates/userform/search.html
{% extends 'base.html' %}
{% load i18n %}


{% block content %}
<div class="card">
    <div class="card-body">
    {% include 'includes/navbar.html' %}
    {% if result %}
        <table class="table table-bordered">
            <thead class="thead-dark">
                <tr> <!-- This is the first row -->
                    <th>{% trans "Kod" %}</th>
                    <th>{% trans "Başlık" %}</th>
                    <th>{% trans "Açıklama" %}</th>
                    <th>{% trans "Link" %}</th>
                    <th>{% trans "Email" %}</th>
                    <th>{% trans "Resim" %}</th>
                </tr>
            </thead>
            <tbody>
                <tr> <!-- This is the second row -->
                    <td>{{result.uuid}}</td>
                    <td>{{result.header}}</td>
                    <td>{{result.description}}</td>
                    <td>{{result.link}}</td>
                    <td>{{result.email}}</td>
                    {% if result.image %}
                        <td><img src="{{result.image.url}}" alt="{% trans "resim" %}" width="100"></td>
                    {% else %}
                        <td class="no-image">{% trans "Resim Bulunamadı" %}</td>
                    {% endif %}
                </tr>
            <tbody>
        </table>
        {% else %}
            {% trans "Kullanıcı Bulunamadı... Lütfen girdiğiniz kodu kontrol ediniz." %}
        {% endif %}
    </div>
</div>

{% endblock content %}